[server]
ip = "127.0.0.1"
port = 9000

[camera]
cam-index = [0]
source = "phone:b0a304df-d581-4b44-a8a9-7f0fccd511d2"
sources = ["phone:b0a304df-d581-4b44-a8a9-7f0fccd511d2"]
manual-setup = true
room-size-m = [4.0, 2.7, 4.0]
show-output = true

[[camera.setup]]
source = "phone:b0a304df-d581-4b44-a8a9-7f0fccd511d2"
position = [-2.0, 1.4, -2.0]
rotation = [45.0, -8.049466975528395, 0.0]
horizontal-fov = 60.000
image-rotation = 0

[tracking]
mode = "single"
smooth = true
pose-quality = "full"
user-height-m = 1.750
vrchat-tracker-set = "stable"
joint-map = "FULLMAP"

[misc]
joy-con-remote = false
