[server]
ip = "127.0.0.1"
port = 9000

[camera]
cam-index = [0]
source = "phone:b101ebe2-d5eb-481b-a098-470d38707ccb"
sources = ["phone:b101ebe2-d5eb-481b-a098-470d38707ccb"]
show-output = true

[tracking]
mode = "single"
smooth = true
pose-quality = "full"
user-height-m = 1.750
vrchat-tracker-set = "stable"
joint-map = "FULLMAP"

[misc]
joy-con-remote = false
